config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :farms
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :bug_types, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug_type.rb
class BugType < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates_uniqueness_of :name
  has_many :farm_bug_types
  has_many :farms, through: :farm_bug_types
end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  has_many :farm_bug_types
  has_many :bug_types, through: :farm_bug_types
end

app/models/farm_bug_type.rb
class FarmBugType < ApplicationRecord
  belongs_to :farm
  belongs_to :bug_type
end

app/models/user.rb
class User < ApplicationRecord   
  before_save { self.email = email.downcase }
  has_secure_password
  has_many :farms, dependent: :destroy
  validates :username, presence: true,
                      uniqueness: { case_sensitive: true },
                      length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 

  def logged_in?
    # The double exclamation marks turn the current_user method / variable into a boolean
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/bug_types_controller.rb
class BugTypesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @bug_types = BugType.paginate(page: params[:page], per_page: 5)
  end

  def show
    @bug_type = BugType.find(params[:id])
    @farms = @bug_type.farms.paginate(page: params[:page], per_page: 5)
  end

  def new
    @bug_type = BugType.new
  end

  def create
    @bug_type = BugType.new(bug_type_params)
    if @bug_type.save
      flash[:notice] = "Bug type was successfully created"
      redirect_to @bug_type
    else
      render 'new'
    end
  end

  def edit 
    @bug_type = BugType.find(params[:id])
  end

  def update
    @bug_type = BugType.find(params[:id])
    if @bug_type.update(bug_type_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to @bug_type 
    else 
      render 'edit'
    end
  end

  private

  def bug_type_params
    params.require(:bug_type).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to bug_types_path
    end
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @farms = Farm.paginate(page: params[:page], per_page: 5)
  end

  def new
    @farm = Farm.new
  end

  def create
    @farm = Farm.new(farm_params)
    @farm.user = current_user
    if @farm.save
      flash[:notice] = "Farm was created successfully."
      redirect_to @farm
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @farm.update(farm_params)
      flash[:notice] = "Farm was updated successfully."
      redirect_to @farm
    else
      render 'edit'
    end
  end

  def destroy
    @farm.destroy
    redirect_to farms_path
  end

  private

  def set_farm
    @farm = Farm.find(params[:id])
  end

  def farm_params
    params.require(:farm).permit(:name, :description, :website, :country, bug_type_ids: [])
  end

  def require_same_user
    if current_user != @farm.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own farm listing"
      redirect_to @farm 
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to farms_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user 
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Bug Farm Listing #{@user.username}, you have successfully signed up"
      redirect_to farms_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @farms = @user.farms.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy 
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to farms_path
  end

  private 
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bug_types/_bug_type.html.erb
<%= link_to bug_type.name, bug_type_path(bug_type), class: "badge badge-pill badge-info mr-1" %>

app/views/bug_types/_form.html.erb
<%= render 'shared/errors', obj: @bug_type %>
<%= form_with(model: @bug_type, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :name, class: "col-sm-2 col-form-label text-light"  %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
    </div>
  </div>

  <div class="form-group row justify-content-center">
    <%= f.submit class: "btn btn-light btn-lg" %>
  </div>
<% end %>

app/views/bug_types/edit.html.erb
<h1 class="text-center mt-4">Edit Bug Type</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <%= render 'form' %>
    </div>
    <div class="mb-3">
      <%= link_to 'Cancel and return to bug types listing', bug_types_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/bug_types/index.html.erb
<h1 class="text-center mt-4">Bug Types</h1>

<div class="flickr_pagination" %>
  <%= will_paginate @bug_types, :container => false %>
</div>

<div class="container">
  <% @bug_types.each do |bug_type| %>
    <div class="row justify-content-md-center">
      <div class="col-12 col-sm-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to bug_type.name, bug_type_path(bug_type), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(bug_type.farms.count, "farm") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(bug_type.created_at) %> ago,
            edited <%= time_ago_in_words(bug_type.updated_at) %> ago</small> 
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination" %>
  <%= will_paginate @bug_types, :container => false %>
</div>

app/views/bug_types/new.html.erb
<h1 class="text-center mt-4">Create a new bug type</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <%= render 'shared/errors', obj: @bug_type %>
      <%= form_with(model: @bug_type, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to 'Cancel and return to farms listing', farms_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/bug_types/show.html.erb
<h1 class="text-center mt-4"><%= @bug_type.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit Bug Type", edit_bug_type_path(@bug_type), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Farms</h3>

<div class="flickr_pagination">
  <%= will_paginate @farms, :container => false %>
</div>

<%= render 'farms/farm' %>

<div class="flickr_pagination">
  <%= will_paginate @farms, :container => false %>
</div>

app/views/farms/_farm.html.erb
<div class="container">
  <% @farms.each do |farm| %>
    <div class="row justify-content-md-center">
      <div class="col-12 col-sm-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if farm.bug_types.any? %>
              <div class="mt-2"><%= render farm.bug_types %></div>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= farm.name %></h5>
            <p class="card-text"><%= truncate(farm.description, length: 100) %></p>
            <%= link_to "website", farm.website, target: "_blank", class:"card_text" %>
            <p class="card-text">Country: <%= farm.country %></p>
            <%= link_to "view", farm_path(farm), class: "btn btn-outline-success" %>
            <% if logged_in? && (farm.user == current_user || current_user.admin?) %>
              <%= link_to "edit", edit_farm_path(farm), class: "btn btn-outline-info" %>
              <%= link_to "delete", farm_path(farm), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(farm.created_at) %> ago,
            edited <%= time_ago_in_words(farm.updated_at) %> ago
              <% if farm.user %>
                - added by <%= link_to farm.user.username, user_path(farm.user) %>
              <% end %>
            </small> 
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/farms/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <%= render 'shared/errors', obj: @farm %>
      <%= form_with(model: @farm, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of the farm" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of the farm" %>
          </div>
        </div>
        
        <div class="form-group row">
          <%= f.label :bug_type, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.collection_select(:bug_type_ids, BugType.all, :id, :name,
             { prompt: "Make your selection from the list below (can be empty)" }, { multiple: true, size: 4, class: "form-control shadow rounded" }) %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :website, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.text_field :website, class: "form-control shadow rounded", placeholder: "website url" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :country, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.text_field :country, class: "form-control shadow rounded", placeholder: "country farm is in" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to 'Cancel and return to farms listing', farms_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/farms/edit.html.erb
<h1 class="text-center mt-4">Edit Farm</h1>
<%= render 'form' %>

app/views/farms/index.html.erb
<h1 class="text-center mt-4">The Farms</h1>

<div class="flickr_pagination" %>
  <%= will_paginate @farms, :container => false %>
</div>
<%= render 'farm' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @farms, :container => false %>
</div>

app/views/farms/new.html.erb
<h1 class="text-center mt-4">List a new farm</h1>
<%= render 'form' %>

app/views/farms/show.html.erb
<div class="container">    
  <div class="row justify-content-md-center">
    <div class="col-12 col-sm-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <% if @farm.bug_types.any? %>
            <div class="mt-2"><%= render @farm.bug_types %></div>
          <% end %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @farm.name %></h5>
          <p class="card-text"><%= @farm.description %></p>
          <%= link_to "website", @farm.website, target: "_blank", class:"card_text" %>
          <p class="card-text">Country: <%= @farm.country %></p>
          <% if logged_in? && (@farm.user == current_user || current_user.admin?) %>
            <%= link_to "edit", edit_farm_path(@farm), class: "btn btn-outline-info" %>
            <%= link_to "delete", farms_path, class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@farm.created_at) %> ago,
          edited <%= time_ago_in_words(@farm.updated_at) %> ago
          <% if @farm.user %>
            added by - <%= link_to @farm.user.username, user_path(@farm.user) %>
          <% end %>  
          </small>
        </div>
      </div>
    </div>
  </div> 
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Matty Plo</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div>
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <%= link_to "Bug Farm Listing", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Farms
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "List a new farm", new_farm_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "Farms Listing", farms_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Bugs
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new bug type", new_bug_type_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View Bug Types", bug_types_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "Admin - " if current_user.admin? %>Profile: <%= current_user.username %> 
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugFarmListing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content"> 
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About the Bug Farm Listing</h1>

<%= link_to 'Farms Listing', farms_path %>
<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron text-light">
    <h1 class="display-4">Welcome to the Bug Farm Listing</h1>
    <p class="lead">Come explore all the wonderful farms across the world harvesting bugs!</p>
    <hr class="my-4">
    <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-secondary rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-sm-2 col-form-label text-light"  %>
          <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to 'Cancel and return to farms listing', farms_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Users</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-12 col-sm-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.farms.count, "farm") %> listed</p>
            <%= link_to "View Profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if user == current_user %>
                <%= link_to "edit", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %></small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Bug Farm Listing</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Farms Listed</h3>

<div class="flickr_pagination">
  <%= will_paginate @farms, :container => false %>
</div>

<%= render 'farms/farm' %>

<div class="flickr_pagination">
  <%= will_paginate @farms, :container => false %>
</div>